# .github/workflows/release.yml
name: Release Versioning
on:
  push:
    branches: [main]

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装 gsemver
      - name: Install gsemver
        run: |
          curl -sL https://github.com/arnaud-deprez/gsemver/releases/latest/download/gsemver-linux-amd64 -o gsemver
          chmod +x gsemver
          sudo mv gsemver /usr/local/bin/

      # 生成新版本并打标签
      - name: Bump version and tag
        run: |
          NEW_VERSION=$(gsemver bump)
          echo "New version: $NEW_VERSION"
          git tag -a $NEW_VERSION -m "Release $NEW_VERSION"
          git push origin $NEW_VERSION
