# .github/workflows/release.yml
name: Release
on:
  push:
    branches: [main]

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gsemver
        run: |
          NEW_VERSION=$(gsemver bump)
          git tag -a $NEW_VERSION -m "Release $NEW_VERSION"
          git push origin $NEW_VERSION
