name: check-website-status

on:
  schedule:
    - cron: "3 1 * * *" # 每小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 检查网站状态
      - name: Check website status
        id: check_status
        run: |
          WEBSITE_URL="https://16860.cn"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $WEBSITE_URL)
          echo "Website status code: $STATUS_CODE"
          echo "status_code=$STATUS_CODE" >> $GITHUB_ENV

      # 保存检查结果
      - name: Save result
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP - Status: $STATUS_CODE" >> website_status.log
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add website_status.log
          git commit -m "fix(log)更新状态日志"
          git push

      # 更新 GitHub Projects 看板
      - name: Update GitHub Projects
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          content: |
            Website check at ${{ steps.check_status.outputs.status_code }}
